"""Add owner_id to Photo

Revision ID: 133993c85cbc
Revises: c1a87ae36cdb
Create Date: 2025-03-10 19:59:45.353853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '133993c85cbc'
down_revision = 'c1a87ae36cdb'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('photo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_photo_owner',  # Ім'я обмеження
            'user',  # Таблиця, на яку посилається ключ
            ['owner_id'],  # Колонка в таблиці `photo`
            ['id']  # Колонка в таблиці `user`
        )



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photo', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('owner_id')

    # ### end Alembic commands ###
